### ISSUE TITLE
Parameters analysis in axon segmentation (EquivDiameter, MajorAxis, MinorAxis, Circularity,...)

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axonseg#12]
Goal : how to get the best discrimination between true & false axons in axon segmentation.

**Comment by tanguyduval** [comment]
Implement a Linear discriminant analysis for that:
http://www.mathworks.com/help/stats/discriminant-analysis.html?refresh=true#brah8i8-1

**Comment by alzaia** [comment]
Ok so thats what its called!

**Comment by tanguyduval** [comment]
Yep!

**Comment by alzaia** [comment]
This is what I get when I do some validation analysis : 

![screen shot 2015-11-30 at 5 41 59 pm](https://cloud.githubusercontent.com/assets/14980394/11486890/de663e88-9789-11e5-867e-572855dac866.png)

**Comment by tanguyduval** [comment]
Looks great! Can you explicit your conclusions plz

-----Original Message-----

**Comment by alzaia** [comment]
I used the Jaccard index here because I can't have the TNs (I only have TP, FP & FN), & I think its a very good indicator in our case. (J = TP/(TP+FP+FN)).

- I dont pay too much attention to the sensitivity values because in the GUI I select the (Sensitivity,Specificity) that minimizes the euclidian distance with (0,1) in the ROC curve.
- It looks like the Jaccard index is always higher for cases where I used a discriminant analysis (which would mean we get better results when using DA). But its not that obvious when comparing the segmented images though.
- It also looks like when using Level Sets, we get slightly better results vs the original axon segmentation methods (higher Jaccard indexes).
- When combining both methods (Extended Minima + Level Sets), its better or similar to the Level Sets results.
- What I didnt expect is that quadratic DA doesnt produce better results than linear DA (but I can explain this because I have less value choices on my ROC curve for the quadratic case).
- Even the manually corrected axons give "only" 0.57 vs the ground truth. So it means even if we get to the perfect axon segmentation, the step after that (myelin segmentation) can validate or invalidate the segmented axons depending on the myelin boundaries, if it touches neighboors,...). So I guess we should also work on the myelin segmentation (for example add myelin thickness boundaries depending on the axon diameter).

**Comment by jcohenadad** [comment]
great investigation! :+1:

**Comment by alzaia** [comment]
I implemented some new axon discrimination parameters by using the information from the neighbourhood (assuming that a true axon is supposed to have a myelin ring surrounding it). So I can use the neighbourhood intensities (both means & std) & the contrast between neighbourhood vs axon candidate. 

So I compared these metrics for true & false axons (manual seg.) for different neighbourhood sizes to see if I can discriminate between the 2 groups. 

![screen shot 2015-12-09 at 6 35 39 pm](https://cloud.githubusercontent.com/assets/14980394/11702397/4a2784d0-9ea4-11e5-898a-ee6583ef7220.png)


It looks like by using a small neighbourhood, I can get a better separation between true vs false axons. I did some tests, it doesn't affect the sensitivity too much if I add these neighbourhood metrics, but it seems to improve the specificity a little. It doesn't make a huge difference, but the more discrimination parameters we can find (specific to our case), the better.

I also did a version updating the neighbourhood screening size, depending on the axon candidate diameter (I used a 0.6 g-ratio to estimate the "myelin thickness").


![screen shot 2015-12-09 at 6 35 49 pm](https://cloud.githubusercontent.com/assets/14980394/11702400/4d89dfce-9ea4-11e5-8756-0299d7610886.png)

**Comment by tanguyduval** [comment]
Looks great!
Also, thank you for the clarity of your figures, really really nice!

Indeed it is important to use the g-ratio --> makes it independant of
pixelsize!

Also in addition to mean and std, you should look at the *skewness*. Your
distribution in the dilated mask is certainly asymmetric due to the
presence of small amount of non-myelin (please check this asumption -->
display histogram in true and false axons).
https://en.wikipedia.org/wiki/Skewness



2015-12-09 18:51 GMT-05:00 alzaia <notifications@github.com>:

**Comment by tanguyduval** [comment]
One problem with discriminant analysis is that the extraction of features is a bit slow... notably the extraction of intensity in each axons (requires a loop over axons)..
