### ISSUE TITLE
[DISTRIB] Check Matlab dependencies (Matlab toolboxes) + Installation instruction

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axonseg#13]

**Comment by tanguyduval** [comment]
Can we remove the dependencies?

**Comment by tanguyduval** [comment]
compile for mac linux and windows

**Comment by tanguyduval** [comment]
Aldo, as-tu une version compilée??

**Comment by alzaia** [comment]
Oui mais après mes tests, je trouve la réaction des exécutables assez bizarre... Le GUI n'a pas de bug, mais il y a des trucs qui agissent différemment (par exemple la myéline segmentée n'apparait juste pas dans le GUI). Pareil pour l'exécutable as_Seg_full_image(), quand je lance ça me demande de sélectionner l'image et le SegParam, mais rien comme résultat. C'est comme une boîte noire, difficile de voir c'est quoi le problème.

**Comment by tanguyduval** [comment]
tu as les erreurs si tu lances par le terminal. Après c'est un code compilé... donc comme le C++ pas de mode debug et faut relancer depuis le début

**Comment by lconcha** [comment]
Hello. I am having trouble using axonSeg, both with the app installer, and with the files downloaded from github.

I am using Ubuntu 14.04 and Matlab 2016a. Same problems appear with Matlab 2013b.  Any help will be much appreciated, below are the steps I followed. I'm looking forward to using axonSeg.

Luis



First, I add axonSeg to my matlab path:
`addpath(genpath('/misc/mansfield/lconcha/software/axonseg/code'))
`
Then, I issue `SegmentationGUI` and get the following error:

```
Error: File: SegmentationGUI.m Line: 1545 Column: 10
Function with duplicate name "LoadSegParam_Callback" cannot be defined.
```

On the other hand, the appInstaller works well, but after selecting the (sample) image and corresponding scheme file, I get the error:
```
Error: File: SegmentationGUI.m Line: 1545 Column: 10
Function with duplicate name "LoadSegParam_Callback" cannot be defined.
 
Undefined variable "GLUE2" or class "GLUE2.Util.isValidImage".

Error in uigetimagefile (line 71)
        elseif ~GLUE2.Util.isValidImage(filename)

Error in SegmentationGUI (line 41)
    FileName= uigetimagefile;

Error in AxonSegApp/startApp (line 63)
			obj.AppHandle = eval('SegmentationGUI');

Error in AxonSegApp (line 40)
      startApp(obj)

Error in appinstall.internal.runapp>execute (line 78)
out = evalin('caller', [script ';']);

Error in appinstall.internal.runapp>runapp13a (line 57)
outobj = execute(fullfile(appinstalldir, [wrapperfile 'App.m']));

Error in appinstall.internal.runapp>runcorrectversion (line 36)
    appobj = runapp13a(appinstalldir);

Error in appinstall.internal.runapp (line 18)
        out = runcorrectversion(appmetadata, appentrypoint, addonmetadatadir);
```

**Comment by alzaia** [comment]
Hello, we are going to do a new release tomorrow, hopefully it should work with the new one. I will keep you updated.

**Comment by lconcha** [comment]
Hello @alzaia , any news on the new release? I cannot see it on the releases tab in github. Was it released in a different way? Thanks.

**Comment by alzaia** [comment]
Hi Luis, I didn't release it yet. I'm still doing some small updates. I will keep you posted. Hopefully it will be ready by the end of the day.

**Comment by alzaia** [comment]
Hi again Luis, our last release is ready. You can find it here :https://github.com/neuropoly/axonseg/releases. Sorry for the delay. If you are experiencing any bugs, please let us know by adding a new issue on our GitHub (go to issues, then click to add new issue). We look forward to hearing your feedback about AxonSeg.

**Comment by alzaia** [comment]
@lconcha we made a minor change again, see release v2.6.

**Comment by lconcha** [comment]
Hello. This is fantastic. I am running the software without any problems so far. Now learning how to use it and testing it with different images. I have to say I am truly impressed by the results so far. 

Thanks a lot for this amazing work.

**Comment by alzaia** [comment]
@lconcha I'm glad you like it so far. Don't hesitate to contact us if you have any bugs/trouble with it. If you follow the as_tutorial.m script, you should get the basics.

**Comment by tanguyduval** [comment]
compiled version --> no more toolboxes
