### ISSUE TITLE
Find Myelin Volume Fraction from axon diameter 

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axonseg#18]
Use a nice SEM image. Find the relation gratio=f(diameter) (try to find refs in literature also).
Then use this relation to find myelin thickness of each axon.

We will use this relation in case of bas myelin segmentation (e.g. myelin exploded/ myelin figures/ resolution too low)

**Comment by tanguyduval** [comment]
Discard problematic points (on the right). Use multiple images. Try to
linearize: plot log(gratio)=f(log(diameter)).

2015-11-16 15:54 GMT-05:00 alzaia <notifications@github.com>:

**Comment by alzaia** [comment]
Found this in the literature. So its supposed to look like this? 
![screen shot 2015-11-17 at 10 31 28 am](https://cloud.githubusercontent.com/assets/14980394/11216111/8898641c-8d17-11e5-9124-6a58517da77c.png)

**Comment by tanguyduval** [comment]
exactly! Great! put the REF please

2015-11-17 10:39 GMT-05:00 alzaia <notifications@github.com>:

**Comment by alzaia** [comment]
[Ikeda 2012 -Relationship between nerve conduction.pdf](https://github.com/neuropoly/axon_segmentation/files/36973/Ikeda.2012.-Relationship.between.nerve.conduction.pdf)

**Comment by alzaia** [comment]
When I keep all our data (combo of 4 different axon segmentations), we have a 'bump', probably due to biais from our segmentation (& maybe from the myelin thickness too). So keeping the whole dataset is not great, as you can see in the left pic. But after some data selection, we get the log regression appearing on the right pic.

![screen shot 2015-11-17 at 5 10 57 pm](https://cloud.githubusercontent.com/assets/14980394/11226691/7ba4c4e8-8d4f-11e5-8ef5-6665269a4f74.png)

**Comment by jcohenadad** [comment]
it's quite confusing to have axon diameter in pix-- i would convert to um

**Comment by alzaia** [comment]
yeah I know but in the axon segmentations I used as dataset, I dont have the pixel size. But I did a quick conversion (for the resolution I used in these images, 1 pix = 0,185 um) so I get this : 
![screen shot 2015-11-17 at 5 40 09 pm](https://cloud.githubusercontent.com/assets/14980394/11227157/6367ca9e-8d52-11e5-9aa3-398237fa00f6.png)

**Comment by alzaia** [comment]
But again, in the data I had we mostly had small axons, & the paper I was referring to is about sciatic nerves, so hard to compare.

**Comment by tanguyduval** [comment]
Something is wrong. If you used the following images I see lot of axons
>5um (>4px by the way):

[image: Images intégrées 1]

2015-11-17 17:42 GMT-05:00 alzaia <notifications@github.com>:

**Comment by jcohenadad** [comment]
we do have pixel resolution from SEM data-- the scale bar is always indicated

**Comment by alzaia** [comment]
This is the result with the whole dataset after updating the x axis (um), it goes from 0 to 10 um : 
![screen shot 2015-11-17 at 6 06 11 pm](https://cloud.githubusercontent.com/assets/14980394/11227763/1a1f5164-8d56-11e5-9a67-72f76f7aacc4.png)

**Comment by tanguyduval** [comment]
Much bettter! Different color for different colors/contrast please!

2015-11-17 18:07 GMT-05:00 alzaia <notifications@github.com>:

**Comment by tanguyduval** [comment]
We can notice the inconsistency for larger axons: their myelin is more
exploded and present "figures"

2015-11-17 18:10 GMT-05:00 Tanguy DUVAL <duvaltanguy@gmail.com>:

**Comment by jcohenadad** [comment]
when i said "1-10um" range, that was a guess estimate, not the actual distribution of axons. You should look at the exact scale bar.

p.s.: guys-- could you please not "reply" to emails, otherwise it accumulates in the github thread-- thanks

**Comment by alzaia** [comment]
Yes I used the exact scale bar. The bigger axons on the image are around 10 um (see screen capture below i.e. one of the biggest axons) : 
![screen shot 2015-11-17 at 6 26 55 pm](https://cloud.githubusercontent.com/assets/14980394/11228187/ef026770-8d58-11e5-8202-cc7e2464fa18.png)

In my case, I'm replying directly on Git. What should we do instead?

**Comment by jcohenadad** [comment]
nice!  results make much more sense now.  Discrepancies from the Ikeda paper probably comes from the fact that you have almost now visible axon with diameter less than 1um. 

However I am wondering how Ikeda et al. could measure g-ratio with axons less than 100nm using optical imaging!

p.s. i was referring to Tanguy for the reply ;-)

**Comment by tanguyduval** [comment]
Very good point! Not specified in the paper. By the way I'm a bit suspicious on some of their data point.. They are strangely aligned no :-)

![image](https://cloud.githubusercontent.com/assets/7785316/11228684/69a62400-8d5c-11e5-97c5-326af6e748bc.png)

**Comment by alzaia** [comment]
Yeah its strange, but in their fig 3 (the histogram distributions) they dont have fibers smaller than 1 um. So it would mean these 1 um fibers have 0,1-0,2 um axons (their smaller g-ratios are around 0,2). But these guys dont do the image processing by themselves, so maybe these are false positives. So our results would make more sense.

**Comment by alzaia** [comment]
I tested the curve fitting with different datasets I had for the SEM data. Its very similar for all datasets, our g-ratios dont vary too much (mostly stay between 0.4 & 0.7). Its easier to get the smaller axons when using a discriminant analysis, thats why the fit has a bigger range. 
![screen shot 2015-11-18 at 11 08 59 am](https://cloud.githubusercontent.com/assets/14980394/11246574/3624e834-8de6-11e5-8ffa-d56f3d1ff1a1.png)
![screen shot 2015-11-18 at 10 59 38 am](https://cloud.githubusercontent.com/assets/14980394/11246576/388b4398-8de6-11e5-84f8-d5dd5b437b4e.png)

**Comment by jcohenadad** [comment]
Aldo, I don't understand: when you say "different dataset" do you mean different images? if not, what do you call different datasets?

**Comment by alzaia** [comment]
No I mean same data but different segmentation processing in fact, sorry :P But I have the same pattern for a 1500x SEM one (small dataset), but this one is manually corrected, so no false positives : 
![screen shot 2015-11-18 at 11 38 49 am](https://cloud.githubusercontent.com/assets/14980394/11248534/9580df0a-8def-11e5-9b91-06237a39daa6.png)
