### ISSUE TITLE
[DOC] Add image of spinal cord tracts in the readme 

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axonseg#19]
![image](https://cloud.githubusercontent.com/assets/7785316/11383065/9d27e15c-92d3-11e5-96ff-cfce871ca534.png)

**Comment by tanguyduval** [comment]
Also Julien if you could send us

**Comment by jcohenadad** [comment]
i would flip the atlas right-left

**Comment by tanguyduval** [comment]
Could you send us the presentation in private msg BTW. Thanks!
