### ISSUE TITLE
[Enhancement] implement AxonSeg using levelsets

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axonseg#3]
cf http://engr.uconn.edu/~cmli/

**Comment by tanguyduval** [comment]
Please Aldo, put your results about the parameters of level set here

**Comment by alzaia** [comment]
This is what you wanted Tanguy : 

![screen shot 2015-11-25 at 12 49 21 pm](https://cloud.githubusercontent.com/assets/14980394/11405001/2f88e8da-9373-11e5-8a94-1bc11cdbb6a2.png)
![screen shot 2015-11-25 at 12 50 05 pm](https://cloud.githubusercontent.com/assets/14980394/11405005/343d424a-9373-11e5-8614-2dc93d6b59da.png)
![screen shot 2015-11-25 at 12 49 58 pm](https://cloud.githubusercontent.com/assets/14980394/11405007/37fdbd92-9373-11e5-985b-a1d68d219288.png)
![screen shot 2015-11-25 at 12 49 49 pm](https://cloud.githubusercontent.com/assets/14980394/11405009/3c5afec2-9373-11e5-946d-d7654356c44b.png)
![screen shot 2015-11-25 at 12 49 37 pm](https://cloud.githubusercontent.com/assets/14980394/11405013/3f9ce866-9373-11e5-8e9a-3621620fbf59.png)
![screen shot 2015-11-25 at 12 49 29 pm](https://cloud.githubusercontent.com/assets/14980394/11405019/4334a1d0-9373-11e5-954c-e5efc3333721.png)

We could allow the user to change mu, nu, c0 & epsilon on the GUI, but that could be kind of a mess... For mu, nu & epsilon, a good range would be between 1 & 0,001.

**Comment by tanguyduval** [comment]
Thanks Aldo
Try with different constrast / compare with actual method (extened minima). Show us only one image per contrast with arrows pointing the differences. One image = one explicit idea/conclusion. 
Put legends/titles/colors

**Comment by tanguyduval** [comment]
What is the status of this investigation? What is the function to use levelset?
Please close the issue when done.

**Comment by tanguyduval** [comment]
C'est dommage, il y a eu une lourde investigation ici mais tu n'as pas fini.
Il n'y a pas de conclusions claires.. est-ce mieux que extended-minima? Il faut utiliser les deux algos sur nos données avec ground truth puis comparer.... En tout cas ce que je vois a l'air très bien, et il me semble que l'on peut fixer la plupart des paramètres.

**Comment by alzaia** [comment]
C'est vrai, je vais m'y remettre prochainement.
