### ISSUE TITLE
Check toolboxes needed to run AxonSeg on Matlab

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axonseg#34]
Undefined function 'fitcdiscr' for input arguments of type 'double'.

Error in Discr_Analysis (line 14)
classifier = fitcdiscr(X,species,'DiscrimType',type,'Cost',Cost_matrix);

Error in as_axonSeg_make_DA_classifier (line 53)
[classifier_init,~] = Discr_Analysis(Stats_1_used, Stats_2_used, [0, 1; 10, 0],type);

Error in SegmentationGUI>DiscriminantAnalysis_Callback (line 1654)
[classifier, handles.parameters,ROC_values] = as_axonSeg_make_DA_classifier(handles.data.Step2_seg,handles.data.DA_final,handles.data.Step1,...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in SegmentationGUI (line 48)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)SegmentationGUI('DiscriminantAnalysis_Callback',hObject,eventdata,guidata(hObject))

 
14  classifier = fitcdiscr(X,species,'DiscrimType',type,'Cost',Cost_matrix);
K>>

Undefined function 'csaps' for input arguments of type 'double'.

Error in myelinInitialSegmention>computeProfileEndpoint (line 242)
pp = csaps(th,yy, 0.99);

Error in myelinInitialSegmention (line 74)
    [radialProfileStartpoint, radialProfileEndpoint] = computeProfileEndpoint(fliplr(currentAxonBoundary{1}), radialProfileLength, numAnglesRadialProfile);

Error in SegmentationGUI>MyelinSeg_Callback (line 1422)
[handles.data.seg] = myelinInitialSegmention(handles.data.Step1, tmp, backBW,0,1,get(handles.PixelSize,'Value'));

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in SegmentationGUI (line 48)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)SegmentationGUI('MyelinSeg_Callback',hObject,eventdata,guidata(hObject))

 
242 pp = csaps(th,yy, 0.99);
K>>

**Comment by tanguyduval** [comment]
same as issue #13
