### ISSUE TITLE
Error Inolving 'ind2rgb8' during full segmentation

### ISSUE THREAD

**Issue by SegDaltonico** [neuropoly/axonseg#38]
Hi! I have experienced the following error after attempting to run a segmentation on a full image. Is there something I can do to fix this? Any help is very much appreciated!

Loop over axons... OK (elapsed time 848.3463 seconds)
done..
Loop over axons...
        7000

        6000

        5000

        4000

        3000

        2000

        1000

done
Elapsed time is 5.440980 seconds.
Undefined function 'ind2rgb8' for input arguments of type 'uint8'.

Error in as_Segmentation_full_image (line 62)
RGB = ind2rgb8(axons_map,hot(maxdiam*10));

Error in SegmentationGUI>go_full_image_Callback (line 1521)
    as_Segmentation_full_image(handles.varargin,[PathName FileName],blocksize,overlap,savedir);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in SegmentationGUI (line 48)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)SegmentationGUI('go_full_image_Callback',hObject,eventdata,guidata(hObject)) 
62  RGB = ind2rgb8(axons_map,hot(maxdiam*10));

**Comment by tanguyduval** [comment]
Hi SegDaltonico,

We are aware of this issue. int2rgb8 is a compiled script.
Which os (mac / windows / Ubuntu / Debian ...) are you using? We are going to add the compatibility to your os.
In the meanwhile you can try to run the command:
````mex ind2rgb8.c````
in the folder [/code/utils](https://github.com/neuropoly/axonseg/tree/master/code/utils) where ind2rgb8.c is located.

Best,
Tanguy

**Comment by SegDaltonico** [comment]
Hi,

Thanks for the quick response. I'm using windows.

**Comment by alzaia** [comment]
Hello, we already have a compiled windows version of ind2rgb8.c. Here it is:
[ind2rgb8.mexw64.zip](https://github.com/neuropoly/axonseg/files/865431/ind2rgb8.mexw64.zip)

You can download it & retry to run the code.

**Comment by SegDaltonico** [comment]
Hi,

Thanks for that alzaia! This error seems to be fixed, but I've gotten another error trying to run a full segmentation:

"
Error using save
Cannot create 'axonlist_full_image.mat' because 'VK22 n4-Columna 3- 46_Segmentation' does not
exist.

Error in as_Segmentation_full_image (line 55)
save([output 'axonlist_full_image.mat'], 'axonlist', 'img', 'PixelSize','-v7.3')
 
55  save([output 'axonlist_full_image.mat'], 'axonlist', 'img', 'PixelSize','-v7.3')
"

"VK22 n4-Columna 3- 46" is the name of the image file I was attempting to segment.

Best,

SegDaltonico

**Comment by tanguyduval** [comment]
thank you for reporting this bug. Please rename your file with no space and signs like - in the name.
I'm correcting this for future release will handle this.

**Comment by tanguyduval** [comment]
aldo can you try the following command on windows please, and see if there is a bug:
`````
output = 'VK22 n4-Columna 3- 46_Segmentation';
mkdir(output)
output=[output filesep];
save([output 'axonlist_full_image.mat'], 'output','-v7.3')
`````

**Comment by alzaia** [comment]
Yes Tanguy, I tested on Windows, there is no bug!

**Comment by tanguyduval** [comment]
Ok thank you Aldo.

SegDaltonico, you might have some writing permission in your current directory..
can you try to run this command on Matlab.
`````
mkdir('VK22 n4-Columna 3- 46_Segmentation')
`````
and see if it makes a directory called VK22 n4-Columna 3- 46_Segmentation

**Comment by tanguyduval** [comment]
@SegDaltonico Can we close this issue?
