### ISSUE TITLE
include axons manually

### ISSUE THREAD

**Issue by vvargas87** [neuropoly/axonseg#43]
Dear Tanguy

I was wondering if there is a way to include the axons that are not labeled by the program

Thank you very much

Victor
INB, UNAM

**Comment by tanguyduval** [comment]
Hi Victor,

I just added this feature. Please download last version on:
https://github.com/neuropoly/axonseg/archive/master.zip

Note that adding axons won't improve the discriminant analysis classifier (if you use it). Only removing axons trains the classifier.

Happy to help,
Best,
Tanguy
