### ISSUE TITLE
Duplicated seg for some axons when generating maps

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axonseg#49]
Ref: https://github.com/neuropoly/histology/issues/1.

**Comment by tanguyduval** [comment]
This problem arises when segmenting badly stiched imaged. This is very specific to our problem (generating maps from a mosaic created by a motorized-stage). The script that creates the issues is not part of AxonSeg but is here https://github.com/neuropoly/histology/blob/6265f60590292726571d1635016569996a551e72/dependencies/batch_postproc.m.

**Comment by jcohenadad** [comment]
i don't understand what the script @tanguyduval is referring to is doing, so i've added an issue here: https://github.com/neuropoly/histology/issues/2
