### ISSUE TITLE
uigetimagefile_v2

### ISSUE THREAD

**Issue by nickolombia98** [neuropoly/axonseg#55]
Hello!
I am new in this, and I am trying to run the program, however, I get an error that says:

Undefined function or variable 'uigetimagefile_v2'.

Error in AxonSeg (line 44)
    FileName= uigetimagefile_v2;
how can I resolve this? thank you very much!

**Comment by jcohenadad** [comment]
hi
sorry for the issue you are experiencing and thank you for the feedback. Have you looked at the more recent and more maintained project, axondeepseg?
https://axondeepseg.readthedocs.io

**Comment by tanguyduval** [comment]
@nickolombia98 concerning your issue, the file located in  `AxonSeg/code/utils/uigetimagefile_v2.m`. I invite you to add AxonSeg subfolders to your Matlab path.
 
But yes... axondeepseg is recommended now
