### ISSUE TITLE
Error in tutorial

### ISSUE THREAD

**Issue by gabirelasanchezzz** [neuropoly/axonseg#56]
Hello, I write here as when I try to run the as_tutorial, in line 20 I get this error

Error using load
Unable to read file 'AxonSeg.fig'. No such file or directory.

Error in matlab.graphics.internal.figfile.FigFile/read (line 31)
hgDataVars = load(filename, '-mat', '-regexp', '^hg[M]');

Error in matlab.graphics.internal.figfile.FigFile

Error in hgload (line 54)
FF = matlab.graphics.internal.figfile.FigFile(filename);

Error in matlab.hg.internal.openfigLegacy (line 57)
    [fig, savedvisible] = hgload(filename, struct('Visible','off'));

Error in gui_mainfcn>local_openfig (line 286)
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);

Error in gui_mainfcn (line 158)
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);

Error in AxonSeg (line 64)
    gui_mainfcn(gui_State, varargin{:});

Error in as_tutorial (line 20)
AxonSeg test_image_OM.tif;

And I don't understand why, I have not modified the code or changed anything. I have tried looking in the AxonSeg file but I dot see why this error arises, I would be thankful if you could help me with this.  
Thanks in advance!

**Comment by tanguyduval** [comment]
Hi gabirelasanchezzz,

You have to add all Axonseg subfolders to your matlab path.
Run the following matlab command:
addpath(genpath(PATHTOAXONSEG))

Hope that helps,
Best

**Comment by gabirelasanchezzz** [comment]
It certainly did. Thank you so much!
Best

**Comment by jcohenadad** [comment]
thank you @tanguyduval !

@gabirelasanchezzz are you aware of the more recent and actively-maintained software [AxonDeepSeg](https://github.com/neuropoly/axondeepseg)?

**Comment by gabirelasanchezzz** [comment]
@jcohenadad I will take a look, thanks!
